version: '3'
services:
  fastapi:
    env_file: .env
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
      image: postgres:15.3-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file: .env
      ports:
        - 5432:5432

volumes:
    postgres_data: